name: Download

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: download file from url
      run: |
        while IFS= read -r line || [ -n "$line" ]; do
            # 忽略空行与注释
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                continue
            fi
            
            url="$line"
            echo "url $url"
            wget $url
        done < urls.txt
        ls -la

    - name: Checkout target branch
      uses: actions/checkout@v2
      with:
        ref: downloaded
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: push files to target branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add .
        git commit -m "update"
        git push origin downloaded